# Ambiente de desenvolvimento
FROM node:22-alpine AS development

WORKDIR /app

# Copia apenas package.json e package-lock.json para instalar deps
COPY package*.json ./

# Instala TUDO (incluindo devDependencies)
RUN npm ci

# Copia o resto do código
COPY . .

# Garante que o binário "next" esteja no PATH
ENV PATH=/app/node_modules/.bin:$PATH

EXPOSE 3000

CMD ["npm", "run", "dev"]

# Builder Stage
FROM node:22-alpine AS builder

WORKDIR /app

COPY package*.json ./

RUN npm ci

COPY . .

RUN npm run build

# Production Stage
FROM node:22-alpine AS production

WORKDIR /app

ENV NODE_ENV=production
ENV HOSTNAME=0.0.0.0
ENV PORT=3000

# Copy the built artifacts from the builder stage
COPY --from=builder --chown=node:node /app/public ./public
COPY --from=builder --chown=node:node /app/.next/standalone ./
COPY --from=builder --chown=node:node /app/.next/static ./.next/static

# Roda sem privilégios de root
USER node

EXPOSE 3000

CMD ["node", "server.js"]
